version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      GEMINI_API_KEY: "AIzaSyD-2kSvF2OlvHdiQPym-Ww-HPzJ76yTwDI"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
